-----------------------------------------------------------------------------
--                             G N A T C O L L                              --
--                                                                          --
--                     Copyright (C) 2014, AdaCore                          --
--                                                                          --
-- This library is free software;  you can redistribute it and/or modify it --
-- under terms of the  GNU General Public License  as published by the Free --
-- Software  Foundation;  either version 3,  or (at your  option) any later --
-- version. This library is distributed in the hope that it will be useful, --
-- but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN- --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE.                            --
--                                                                          --
-- As a special exception under Section 7 of GPL version 3, you are granted --
-- additional permissions described in the GCC Runtime Library Exception,   --
-- version 3.1, as published by the Free Software Foundation.               --
--                                                                          --
-- You should have received a copy of the GNU General Public License and    --
-- a copy of the GCC Runtime Library Exception along with this program;     --
-- see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see    --
-- <http://www.gnu.org/licenses/>.                                          --
--                                                                          --
------------------------------------------------------------------------------

--  An example test driver.
--  Such code would be automatically generated by gnattdd

with BDD;               use BDD;
with BDD.Formatters;    use BDD.Formatters;
with BDD.Parser;        use BDD.Parser;
with BDD.Runner;        use BDD.Runner;
with GNATCOLL.Terminal; use GNATCOLL.Terminal;
with GNATCOLL.Traces;   use GNATCOLL.Traces;
with GNATCOLL.VFS;      use GNATCOLL.VFS;

procedure Driver is
   Features : BDD.Runner.Feature_Runner;
   Parser   : BDD.Parser.Feature_Parser;
   Format   : constant access BDD.Formatters.Formatter'Class :=
     new BDD.Formatters.Formatter_Full;
   Term     : constant Terminal_Info_Access := new Terminal_Info;
begin
   GNATCOLL.Traces.Parse_Config_File;

   Features.Discover (+BDD.Features_File_Ext.all, BDD.Features_Directory);

   Term.Init_For_Stdout (Colors => Auto);
   Format.Init (Term);

   Features.Run (Format, Parser);
end Driver;
