
--  An example test driver.
--  Such code would be automatically generated by gnattdd

with Ada.Text_IO;     use Ada.Text_IO;
with BDD.Runner;      use BDD.Runner;
with BDD.Features;    use BDD.Features;
with GNATCOLL.Traces; use GNATCOLL.Traces;
with GNATCOLL.VFS;    use GNATCOLL.VFS;

procedure Driver is
   procedure Run_Feature (F : Feature);
   procedure Run_Feature (F : Feature) is
   begin
      Put_Line ("MANU Found feature: " & F.File.Display_Full_Name
                & " => " & F.Name);
   end Run_Feature;

   Features : BDD.Runner.Feature_Runner;
begin
   GNATCOLL.Traces.Parse_Config_File;
   Features.Discover (".feature", Create_From_Base ("features"));
   Features.For_Each (Run_Feature'Access);
end Driver;
