
--  An example test driver.
--  Such code would be automatically generated by gnattdd

with GNATTDD.Features;   use GNATTDD.Features;

procedure Driver is
begin
   GNATTDD.Features.Discover_Features_Files (".");

end Driver;
